# Generated by Django 5.1.6 on 2025-02-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
