# Generated by Django 5.1.6 on 2025-02-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manipulate_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
    ]
