# Generated by Django 5.1.6 on 2025-03-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manipulate_book', '0002_rename_book_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
