# Generated by Django 5.1.6 on 2025-03-08 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 17, 15, 27, 818669, tzinfo=datetime.timezone.utc)),
        ),
    ]
