# Generated by Django 5.1.6 on 2025-03-24 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0010_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 14, 44, 54, 376574)),
        ),
    ]
